/* Generated by IDL compiler version FreeDCE 1.1.0.7 with GNU Flex/Bison */
#ifndef ICertPassage_v0_0_included
#define ICertPassage_v0_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif
#include <dce/rpc.h>

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
#ifndef dtype_v0_0_included
#include <dtyp.h>
#endif
typedef struct _CERTTRANSBLOB {
ULONG cb;
BYTE *pb;
} CERTTRANSBLOB;
extern DWORD CertServerRequest(
    /* [in] */ handle_t h,
    /* [in] */ DWORD dwFlags,
    /* [in] */ idl_ushort_int *pwszAuthority,
    /* [in, out] */ DWORD *pdwRequestId,
    /* [out] */ DWORD *pdwDisposition,
    /* [in] */ CERTTRANSBLOB *pctbAttribs,
    /* [in] */ CERTTRANSBLOB *pctbRequest,
    /* [out] */ CERTTRANSBLOB *pctbCert,
    /* [out] */ CERTTRANSBLOB *pctbEncodedCert,
    /* [out] */ CERTTRANSBLOB *pctbDispositionMessage
);
typedef struct ICertPassage_v0_0_epv_t {
	DWORD (*CertServerRequest)(
    /* [in] */ handle_t h,
    /* [in] */ DWORD dwFlags,
    /* [in] */ idl_ushort_int *pwszAuthority,
    /* [in, out] */ DWORD *pdwRequestId,
    /* [out] */ DWORD *pdwDisposition,
    /* [in] */ CERTTRANSBLOB *pctbAttribs,
    /* [in] */ CERTTRANSBLOB *pctbRequest,
    /* [out] */ CERTTRANSBLOB *pctbCert,
    /* [out] */ CERTTRANSBLOB *pctbEncodedCert,
    /* [out] */ CERTTRANSBLOB *pctbDispositionMessage
);
} ICertPassage_v0_0_epv_t;
extern rpc_if_handle_t ICertPassage_v0_0_c_ifspec;
extern rpc_if_handle_t ICertPassage_v0_0_s_ifspec;

#ifdef __cplusplus
    }
#endif

#endif
